// <auto-generated />
using System;
using ArkWallet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArkWallet.Migrations
{
    [DbContext(typeof(ArkWalletDbContext))]
    [Migration("20260903064200_MailMessages")]
    partial class MailMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArkWallet.Domain.Entities.BalanceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BalanceInTokens")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LongOrderReserveBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MainBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ShortOrderReserveBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("SnapshotDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("numeric");

                    b.Property<long>("TraderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TraderId", "SnapshotDateTime");

                    b.ToTable("BalanceSnapshots");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.CharacterToken", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSupply")
                        .HasColumnType("integer");

                    b.HasKey("Symbol");

                    b.ToTable("CharacterTokens");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.Gift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("PriceAtSend")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RecipientId")
                        .HasColumnType("bigint");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.GlobalGoal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AchievedCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Actual")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Progress")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Target")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GlobalGoals");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.GlobalGoalHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("AmountForReward")
                        .HasColumnType("numeric");

                    b.Property<long>("GoalId")
                        .HasColumnType("bigint");

                    b.Property<string>("SymbolForReward")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Target")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GlobalGoalHistories");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.GlobalGoalStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountForReward")
                        .HasColumnType("numeric");

                    b.Property<long>("GoalId")
                        .HasColumnType("bigint");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SymbolForReward")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Target")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("GoalId", "StepNumber")
                        .IsUnique();

                    b.ToTable("GlobalGoalSteps");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MailMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("AmountForReward")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SymbolForReward")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TraderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MailMessages");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MarketMakerBot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BasePower")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("NextPowerChange")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextRebalance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TraderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MarketMakerBots");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MiningGlobalRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BaseTokenMiningSpeed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CurrentCoefficient")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FutureCoefficient")
                        .HasColumnType("numeric");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenId")
                        .IsUnique();

                    b.ToTable("MiningGlobalRules");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MiningMachine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Efficiency")
                        .HasColumnType("numeric");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActiveForSale")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Reusability")
                        .HasColumnType("numeric");

                    b.Property<int>("SwitchingTime")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MiningMachines");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MiningMachineRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MiningCoefficient")
                        .HasColumnType("numeric");

                    b.Property<long>("MiningMachineId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTokenId");

                    b.HasIndex("MiningMachineId", "CharacterTokenId")
                        .IsUnique();

                    b.ToTable("MiningMachineRules");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MiningMachineSlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Efficiency")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("EndSwitchingDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("MiningGlobalRuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartSwitchingDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SwitchingTime")
                        .HasColumnType("integer");

                    b.Property<string>("TokenId")
                        .HasColumnType("text");

                    b.Property<decimal>("TokensAmountCollected")
                        .HasColumnType("numeric");

                    b.Property<long>("TraderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MiningGlobalRuleId");

                    b.HasIndex("Status");

                    b.HasIndex("TokenId");

                    b.HasIndex("TraderId");

                    b.ToTable("MiningMachineSlots");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MiningMachineSlotRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MiningCoefficient")
                        .HasColumnType("numeric");

                    b.Property<long>("MiningMachineSlotId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTokenId");

                    b.HasIndex("MiningMachineSlotId", "CharacterTokenId")
                        .IsUnique();

                    b.ToTable("MiningMachineSlotRules");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.PortfolioItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("AverageBuyPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageReservePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageSellPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ReserveQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("SellingQuantity")
                        .HasColumnType("integer");

                    b.Property<long>("TraderTelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTokenId");

                    b.HasIndex("TraderTelegramId");

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.PriceCandle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTokenId");

                    b.ToTable("PriceCandles");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.Trade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("BuyerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CharacterTokenId");

                    b.HasIndex("SellerId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.TradeOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("AverageExecutePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilledQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TraderTelegramId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTokenId");

                    b.HasIndex("TraderTelegramId");

                    b.ToTable("TradeOrders");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.Trader", b =>
                {
                    b.Property<long>("TelegramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TelegramId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NotificationOn")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("TelegramId");

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("ArkWallet.Infrastructure.Data.AccessSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("BlackList")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupBlackList")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupWhiteList")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGlobalAccessEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGroupAccessEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("WhiteList")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("AccessSettings");
                });

            modelBuilder.Entity("ArkWallet.Infrastructure.Data.AppState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("AppStates");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.BalanceSnapshot", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.Trader", "Trader")
                        .WithMany("BalanceSnapshots")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.GlobalGoalHistory", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.GlobalGoal", null)
                        .WithMany("Histories")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.GlobalGoalStep", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.GlobalGoal", null)
                        .WithMany("Steps")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MiningGlobalRule", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CharacterToken");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MiningMachineRule", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArkWallet.Domain.Entities.MiningMachine", "MiningMachine")
                        .WithMany("MiningMachineRules")
                        .HasForeignKey("MiningMachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CharacterToken");

                    b.Navigation("MiningMachine");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MiningMachineSlot", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.MiningGlobalRule", "MiningGlobalRule")
                        .WithMany()
                        .HasForeignKey("MiningGlobalRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArkWallet.Domain.Entities.CharacterToken", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArkWallet.Domain.Entities.Trader", null)
                        .WithMany()
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MiningGlobalRule");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MiningMachineSlotRule", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArkWallet.Domain.Entities.MiningMachineSlot", "MiningMachineSlot")
                        .WithMany("MiningMachineSlotRules")
                        .HasForeignKey("MiningMachineSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterToken");

                    b.Navigation("MiningMachineSlot");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.PortfolioItem", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkWallet.Domain.Entities.Trader", "Trader")
                        .WithMany("Portfolio")
                        .HasForeignKey("TraderTelegramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterToken");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.PriceCandle", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterToken");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.Trade", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.Trader", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkWallet.Domain.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkWallet.Domain.Entities.Trader", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("CharacterToken");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.TradeOrder", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkWallet.Domain.Entities.Trader", "Trader")
                        .WithMany("Orders")
                        .HasForeignKey("TraderTelegramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterToken");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.GlobalGoal", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MiningMachine", b =>
                {
                    b.Navigation("MiningMachineRules");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MiningMachineSlot", b =>
                {
                    b.Navigation("MiningMachineSlotRules");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.Trader", b =>
                {
                    b.Navigation("BalanceSnapshots");

                    b.Navigation("Orders");

                    b.Navigation("Portfolio");
                });
#pragma warning restore 612, 618
        }
    }
}
