using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArkWallet.Migrations
{
    /// <inheritdoc />
    public partial class MigrateTraderToIdPk : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Снять все FK, ссылающиеся на старый PK Traders (TelegramId).
            migrationBuilder.DropForeignKey(
                name: "FK_BalanceSnapshots_Traders_TraderId",
                table: "BalanceSnapshots");

            migrationBuilder.DropForeignKey(
                name: "FK_MiningMachineSlots_Traders_TraderId",
                table: "MiningMachineSlots");

            migrationBuilder.DropForeignKey(
                name: "FK_PortfolioItems_Traders_TraderTelegramId",
                table: "PortfolioItems");

            migrationBuilder.DropForeignKey(
                name: "FK_SubscriptionPurchaseHistory_Traders_TraderId",
                table: "SubscriptionPurchaseHistory");

            migrationBuilder.DropForeignKey(
                name: "FK_TradeOrders_Traders_TraderTelegramId",
                table: "TradeOrders");

            migrationBuilder.DropForeignKey(
                name: "FK_Trades_Traders_BuyerId",
                table: "Trades");

            migrationBuilder.DropForeignKey(
                name: "FK_Trades_Traders_SellerId",
                table: "Trades");

            // 2. Снять старый PK (TelegramId).
            migrationBuilder.DropPrimaryKey(
                name: "PK_Traders",
                table: "Traders");

            // 3. Переименовать FK-колонки зависимых таблиц (TraderTelegramId -> TraderId).
            migrationBuilder.RenameColumn(
                name: "TraderTelegramId",
                table: "TradeOrders",
                newName: "TraderId");

            migrationBuilder.RenameIndex(
                name: "IX_TradeOrders_TraderTelegramId",
                table: "TradeOrders",
                newName: "IX_TradeOrders_TraderId");

            migrationBuilder.RenameColumn(
                name: "TraderTelegramId",
                table: "PortfolioItems",
                newName: "TraderId");

            migrationBuilder.RenameIndex(
                name: "IX_PortfolioItems_TraderTelegramId",
                table: "PortfolioItems",
                newName: "IX_PortfolioItems_TraderId");

            // 4. TelegramId становится nullable (только для людей).
            //    Сначала снять IDENTITY (identity-колонки в PostgreSQL неявно NOT NULL,
            //    и DROP NOT NULL без DROP IDENTITY невозможен), затем сделать nullable.
            migrationBuilder.Sql(
                """
                ALTER TABLE "Traders" ALTER COLUMN "TelegramId" DROP IDENTITY;
                ALTER TABLE "Traders" ALTER COLUMN "TelegramId" DROP NOT NULL;
                """);

            // 5. Новый суррогатный PK Id (identity). PostgreSQL сам присвоит значения 1..N существующим строкам.
            migrationBuilder.Sql("ALTER TABLE \"Traders\" ADD COLUMN \"Id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;");

            // 6. Признак бота.
            migrationBuilder.AddColumn<bool>(
                name: "IsBot",
                table: "Traders",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            // 7. Новый PK по Id.
            migrationBuilder.AddPrimaryKey(
                name: "PK_Traders",
                table: "Traders",
                column: "Id");

            // 8. Перенумерация всех ссылок в зависимых таблицах со старого TelegramId на новый Id.
            //    Важно: выполняется, пока TelegramId у трейдеров ещё сохранён.
            migrationBuilder.Sql(
                """
                UPDATE "BalanceSnapshots" x SET "TraderId" = t."Id" FROM "Traders" t WHERE x."TraderId" = t."TelegramId";
                UPDATE "MiningMachineSlots" x SET "TraderId" = t."Id" FROM "Traders" t WHERE x."TraderId" = t."TelegramId";
                UPDATE "PortfolioItems" x SET "TraderId" = t."Id" FROM "Traders" t WHERE x."TraderId" = t."TelegramId";
                UPDATE "SubscriptionPurchaseHistory" x SET "TraderId" = t."Id" FROM "Traders" t WHERE x."TraderId" = t."TelegramId";
                UPDATE "TradeOrders" x SET "TraderId" = t."Id" FROM "Traders" t WHERE x."TraderId" = t."TelegramId";
                UPDATE "Trades" x SET "BuyerId" = t."Id" FROM "Traders" t WHERE x."BuyerId" = t."TelegramId";
                UPDATE "Trades" x SET "SellerId" = t."Id" FROM "Traders" t WHERE x."SellerId" = t."TelegramId";
                UPDATE "MarketMakerBots" x SET "TraderId" = t."Id" FROM "Traders" t WHERE x."TraderId" = t."TelegramId";
                """);

            // 9. Проверка целостности перед пересозданием FK: не должно остаться «висячих» ссылок.
            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF EXISTS (SELECT FROM "BalanceSnapshots" x LEFT JOIN "Traders" t ON t."Id" = x."TraderId" WHERE t."Id" IS NULL) THEN RAISE EXCEPTION 'Dangling TraderId in BalanceSnapshots'; END IF;
                    IF EXISTS (SELECT FROM "MiningMachineSlots" x LEFT JOIN "Traders" t ON t."Id" = x."TraderId" WHERE t."Id" IS NULL) THEN RAISE EXCEPTION 'Dangling TraderId in MiningMachineSlots'; END IF;
                    IF EXISTS (SELECT FROM "PortfolioItems" x LEFT JOIN "Traders" t ON t."Id" = x."TraderId" WHERE t."Id" IS NULL) THEN RAISE EXCEPTION 'Dangling TraderId in PortfolioItems'; END IF;
                    IF EXISTS (SELECT FROM "SubscriptionPurchaseHistory" x LEFT JOIN "Traders" t ON t."Id" = x."TraderId" WHERE t."Id" IS NULL) THEN RAISE EXCEPTION 'Dangling TraderId in SubscriptionPurchaseHistory'; END IF;
                    IF EXISTS (SELECT FROM "TradeOrders" x LEFT JOIN "Traders" t ON t."Id" = x."TraderId" WHERE t."Id" IS NULL) THEN RAISE EXCEPTION 'Dangling TraderId in TradeOrders'; END IF;
                    IF EXISTS (SELECT FROM "Trades" x LEFT JOIN "Traders" t ON t."Id" = x."BuyerId" WHERE t."Id" IS NULL) THEN RAISE EXCEPTION 'Dangling BuyerId in Trades'; END IF;
                    IF EXISTS (SELECT FROM "Trades" x LEFT JOIN "Traders" t ON t."Id" = x."SellerId" WHERE t."Id" IS NULL) THEN RAISE EXCEPTION 'Dangling SellerId in Trades'; END IF;
                    IF EXISTS (SELECT FROM "MarketMakerBots" x LEFT JOIN "Traders" t ON t."Id" = x."TraderId" WHERE t."Id" IS NULL) THEN RAISE EXCEPTION 'Dangling TraderId in MarketMakerBots'; END IF;
                END $$;
                """);

            // 10. Старые боты переезжают на новую семантику: IsBot=true, TelegramId=null, NotificationOn=false.
            //     (боты-трейдеры определяются по имени: MarketMakerBot_<symbol> и WallBlocker)
            migrationBuilder.Sql(
                """
                UPDATE "Traders" SET "IsBot" = true, "TelegramId" = NULL, "NotificationOn" = false
                WHERE "Username" = 'WallBlocker' OR "Username" LIKE 'MarketMakerBot!_%' ESCAPE '!';
                """);

            // 11. Уникальный индекс по TelegramId (допускает NULL — у ботов).
            migrationBuilder.CreateIndex(
                name: "IX_Traders_TelegramId",
                table: "Traders",
                column: "TelegramId",
                unique: true);

            // 12. Восстановить FK на новый PK (Id).
            migrationBuilder.AddForeignKey(
                name: "FK_BalanceSnapshots_Traders_TraderId",
                table: "BalanceSnapshots",
                column: "TraderId",
                principalTable: "Traders",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_MiningMachineSlots_Traders_TraderId",
                table: "MiningMachineSlots",
                column: "TraderId",
                principalTable: "Traders",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PortfolioItems_Traders_TraderId",
                table: "PortfolioItems",
                column: "TraderId",
                principalTable: "Traders",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_SubscriptionPurchaseHistory_Traders_TraderId",
                table: "SubscriptionPurchaseHistory",
                column: "TraderId",
                principalTable: "Traders",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_TradeOrders_Traders_TraderId",
                table: "TradeOrders",
                column: "TraderId",
                principalTable: "Traders",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Trades_Traders_BuyerId",
                table: "Trades",
                column: "BuyerId",
                principalTable: "Traders",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Trades_Traders_SellerId",
                table: "Trades",
                column: "SellerId",
                principalTable: "Traders",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            throw new NotSupportedException(
                "Откат миграции MigrateTraderToIdPk автоматически невозможен: данные необратимо преобразованы " +
                "(у старых ботов очищен TelegramId, ссылки перенумерованы на новый Id). " +
                "Восстановление — только из резервной копии БД.");
        }
    }
}