// <auto-generated />
using System;
using ArkWallet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArkWallet.Migrations
{
    [DbContext(typeof(ArkWalletDbContext))]
    partial class ArkWalletDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ArkWallet.Entities.CharacterToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSupply")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CharacterTokens");
                });

            modelBuilder.Entity("ArkWallet.Entities.PortfolioItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageBuyPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TraderTelegramId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTokenId");

                    b.HasIndex("TraderTelegramId");

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("ArkWallet.Entities.Trade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("BuyerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SellerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CharacterTokenId");

                    b.HasIndex("SellerId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("ArkWallet.Entities.TradeOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilledQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TraderTelegramId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTokenId");

                    b.HasIndex("TraderTelegramId");

                    b.ToTable("TradeOrders");
                });

            modelBuilder.Entity("ArkWallet.Entities.Trader", b =>
                {
                    b.Property<long>("TelegramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("TelegramId");

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("ArkWallet.Entities.PortfolioItem", b =>
                {
                    b.HasOne("ArkWallet.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkWallet.Entities.Trader", "Trader")
                        .WithMany("Portfolio")
                        .HasForeignKey("TraderTelegramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterToken");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("ArkWallet.Entities.Trade", b =>
                {
                    b.HasOne("ArkWallet.Entities.Trader", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkWallet.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkWallet.Entities.Trader", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("CharacterToken");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("ArkWallet.Entities.TradeOrder", b =>
                {
                    b.HasOne("ArkWallet.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkWallet.Entities.Trader", "Trader")
                        .WithMany("Orders")
                        .HasForeignKey("TraderTelegramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterToken");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("ArkWallet.Entities.Trader", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Portfolio");
                });
#pragma warning restore 612, 618
        }
    }
}
