// <auto-generated />
using System;
using ArkWallet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArkWallet.Migrations
{
    [DbContext(typeof(ArkWalletDbContext))]
    partial class ArkWalletDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AppState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppStates");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.BalanceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BalanceInTokens")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LongOrderReserveBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MainBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShortOrderReserveBalance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotDateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("TEXT");

                    b.Property<long>("TraderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TraderId");

                    b.ToTable("BalanceSnapshots");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.CharacterToken", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSupply")
                        .HasColumnType("INTEGER");

                    b.HasKey("Symbol");

                    b.ToTable("CharacterTokens");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.MarketMakerBot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePower")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NextPowerChange")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextRebalance")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TraderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MarketMakerBots");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.PortfolioItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageBuyPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageReservePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageSellPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReserveQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TraderTelegramId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTokenId");

                    b.HasIndex("TraderTelegramId");

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.PriceCandle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTokenId");

                    b.ToTable("PriceCandles");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.Trade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("BuyerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SellerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CharacterTokenId");

                    b.HasIndex("SellerId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.TradeOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageExecutePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterTokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilledQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TraderTelegramId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTokenId");

                    b.HasIndex("TraderTelegramId");

                    b.ToTable("TradeOrders");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.Trader", b =>
                {
                    b.Property<long>("TelegramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("TelegramId");

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.BalanceSnapshot", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.Trader", "Trader")
                        .WithMany("BalanceSnapshots")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.PortfolioItem", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkWallet.Domain.Entities.Trader", "Trader")
                        .WithMany("Portfolio")
                        .HasForeignKey("TraderTelegramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterToken");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.PriceCandle", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterToken");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.Trade", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.Trader", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkWallet.Domain.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkWallet.Domain.Entities.Trader", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("CharacterToken");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.TradeOrder", b =>
                {
                    b.HasOne("ArkWallet.Domain.Entities.CharacterToken", "CharacterToken")
                        .WithMany()
                        .HasForeignKey("CharacterTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkWallet.Domain.Entities.Trader", "Trader")
                        .WithMany("Orders")
                        .HasForeignKey("TraderTelegramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterToken");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("ArkWallet.Domain.Entities.Trader", b =>
                {
                    b.Navigation("BalanceSnapshots");

                    b.Navigation("Orders");

                    b.Navigation("Portfolio");
                });
#pragma warning restore 612, 618
        }
    }
}
